### ISSUE TITLE
ŇYC TO NEDJĚLA

### ISSUE THREAD

**Issue by kouks** [bausano/solitaire#1]
MUŽU JEN KLYKAT NA KARTI A NYC JYNEHO ADMYNE PODYVEJ SE NA TO PLZ

**Comment by bausano** [comment]
@kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks @kouks  JA SEM EŽTJE NENAHRAVAL NOVJEJŠÝ VESRI, KDE TAM JE ZACHRNUT I TO TAM SORRY
